### ISSUE TITLE
Issue with Ks

### ISSUE THREAD

**Issue by jpgattuso** [jpgattuso/seacarb-git#23]
I get the error below on glodap data centered on the Med and Red Seas. The code of Ks.R lines 92-98 is weird. I believe that you forgot to distinguish to take into consideration the formulations on Dickson and Khoo. Let me know. 

Cheers,
Jean-Pierre

-----------------------------------------------------------------------------
Error in if (any(is_w & (T > 45 | S > 45 | T < 0 | S < 5))) warning("S and/or T is outside the range of validity of the formulations available for Ks in seacarb.") : 
  missing value where TRUE/FALSE needed

**Comment by jamesorr** [comment]
It is only missing "curly braces" opening just before 'warning' and closing at the end of the line.  I have made Pull request #24 to fix this problem.  

My addition of 'is_w' should not affect any of the previous logic regarding the 2 formulations.  I only added 'is_w' to the conditional's and nothing else.  If that logic was wrong to start with though, I did not fix it.
