### ISSUE TITLE
buffesm does not work

### ISSUE THREAD

**Issue by jpgattuso** [jpgattuso/seacarb-git#29]
See, for example, the first example mentioned in the man file:

buffesm(flag=8, var1=8.2, var2=0.00234, S=35, T=25, P=0, Pt=0, Sit=0, pHscale="T", kf="pf", k1k2="l", b="u74")

It returns NaNs

**Comment by jamesorr** [comment]
This issue was fixed by a Pull request on Nov. 21 that you later integrted into branch 3.1.1.  It has not yet been merged into the master branch.  Please merge and close this issue.
