### ISSUE TITLE
Issue raised by CRAN

### ISSUE THREAD

**Issue by jpgattuso** [jpgattuso/seacarb-git#54]
Dear maintainers,

This concerns the CRAN packages

[includes seacarb]

maintained by one of you:

[includes Jean-Pierre Gattuso]

R currently only emits a warning when if/while statement is used with a condition of length greater than one, e.g.

if (c(1,2)>0) TRUE [1] TRUE Warning message: In if (c(1, 2) > 0) TRUE : the condition has length > 1 and only the first element will be used

However, such cases are almost always programming errors, and hence this warning will soon be turned into a runtime error. This can already be done in current R-devel by setting environment variable R_CHECK_LENGTH_1_CONDITION=true to make it easier to spot these cases. And this is already done in certain CRAN checks.

A condition of length greater than one has been detected while running tests of your package (and the if/while statement involved was in the code of your package, so it is unlikely that this would have been caused by a dependent package). Detailed reports can be found at

https://github.com/kalibera/rifcond

I’ve modified R slightly to give more detailed debugging information in case of this error, so hopefully the outputs will be useful in finding the cause of the problem. In either case, one can reproduce the problem in normal R-devel via R_CHECK_LENGTH_1_CONDITION=true or in a released version of R by looking at warnings.

Please check out the reports and fix this in your package(s) as soon as possible. In the unlikely case this is caused by a dependent package, please report to the maintainer of that package.

Thank you, Tomas

**Comment by umihoshijima** [comment]
Could you not replace: 

```
if(c(1,2)>0){
...
}
```

with:

```
if(sum(c(1,2)>0)){
...
}
```

???

**Comment by jpgattuso** [comment]
The message received provided an example which is not part of the seacarb code.

**Comment by pieterprovoost** [comment]
According to the [error report](https://github.com/kalibera/rifcond/blob/master/outputs/seacarb.Rcheck/seacarb-Ex.Rout#L1076), the issue is in [carbfull.R#758](https://github.com/cran/seacarb/blob/master/R/carbfull.R#L758).

In the `buffergen` example code, `gas` is a vector of length > 1:

```R
gas <- c("potential", "potential", "potential")

buffergen(flag=flag, var1=var1, var2=var2, S=S, T=T, P=P, Pt=Pt, Sit=Sit, 
  kf=kf, k1k2=k1k2, pHscale=pHscale, b=b, gas=gas, NH4t=NH4t, HSt=HSt)
```

`buffergen` calls `carbfull` with the same `gas` argument, which then on line [carbfull.R#758](https://github.com/cran/seacarb/blob/master/R/carbfull.R#L758) does this check:

```R
if(gas=="insitu")
```

This will generate the warning and ignore all values of `gas` except the first one.

**Comment by jpgattuso** [comment]
Great to hear from you Pieter! I hope you are doing well.

I have replaced line 172 of buffergen.Rd by gas <- c("potential"). All seems well. We'll see whether it bounces back when submitted to CRAN.

**Comment by jpgattuso** [comment]
I think that the issue is now fixed and can be closed.
