### ISSUE TITLE
Error in carb package

### ISSUE THREAD

**Issue by jordanhollarsmith** [jpgattuso/seacarb-git#60]
The carb package releases an error <argument "var1" is missing, with no default>.

This error appears when I use the example df (seacarb_test_P300, seacarb_test_P0, or the x1 x2 df), or my own dataframe that is formatted correctly according to the guidelines for this package. I tried with flag formatted as a number and factor.

> str(dframe)
'data.frame':	225700 obs. of  9 variables:
 $ flag: num  24 24 24 24 24 24 24 24 24 24 ...
 $ var1: num  500 496 489 491 496 ...
 $ var2: num  0.00229 0.00229 0.00229 0.00229 0.00229 ...
 $ S   : num  33.4 33.4 33.4 33.4 33.4 ...
 $ T   : num  17.9 17.9 18 18 18.1 ...
 $ P   : num  0 0 0 0 0 0 0 0 0 0 ...
 $ Pt  : num  0 0 0 0 0 0 0 0 0 0 ...
 $ Sit : num  0 0 0 0 0 0 0 0 0 0 ...
 $ k1k2: Factor w/ 1 level "m10": 1 1 1 1 1 1 1 1 1 1 ...

> carb(dframe)
Error in carb(dframe) : argument "var1" is missing, with no default

**Comment by jpgattuso** [comment]
I am glad it works!

Jean-Pierre
